export const  restaurantList  = [
    {
      id:1,
      name: 'Veeresh Restaurant',
      place: 'Bangalore',
      breakfast: 'Dosa & Idli & Wada',
      dinner: 'Paneer & Kaju Kadai & Butter Naan',
      rating: 4.5,
    },
    {
      id:2,
      name: 'Saravana Bhavan',
      place: 'Chennai',
      breakfast: 'Masala Dosa & Idli & Vada',
      dinner: 'Vegetable Biryani & Gobi Manchurian',
      rating: 3.97
    },
    {
      id:3,
      name: 'Paradise Biryani',
      place: 'Hyderabad',
      breakfast: 'Not Available',
      dinner: 'Uttappa',
      rating: 4.8,
    },
    {
      id:4,
      name: 'The Grill House',
      place: 'New York',
      breakfast: 'Pancakes & Omelette',
      dinner: 'Steak & Lobster',
      rating: 4.7,
    },
    {
      id:5,
      name: 'Mediterranean Delight',
      place: 'Athens',
      breakfast: 'Greek Yogurt & Honey',
      dinner: 'Moussaka & Souvlaki',
      rating: 3.8,
    },
    {
      id:6,
      name: 'Bollywood Bites',
      place: 'Mumbai',
      breakfast: 'Vada Pav & Pav Bhaji',
      dinner: 'Dal & Roti',
      rating: 2.9,
    },
    {
      id:7,
      name: 'Sushi Sensation',
      place: 'Tokyo',
      breakfast: 'Not Available',
      dinner: 'Sashimi & Tempura',
      rating: 3.45,
    },
    {
      id:8,
      name: 'Casa Italia',
      place: 'Rome',
      breakfast: 'Not Available',
      dinner: 'Lasagna & Tiramisu',
      rating: 4.6,
    },
    {
      id:9,
      name: 'Thai Orchid',
      place: 'Bangkok',
      breakfast: 'Pad Thai & Spring Rolls',
      dinner: 'Green Curry & Mango Sticky Rice',
      rating: 1.89,
    }
  ];